// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"time"
)

type Feed struct {
	ID            int32
	Name          string
	LastPostTitle string
	FeedUrl       string
	WebhookUrl    string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
